<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown-dealership</name>
   <tag></tag>
   <elementGuidId>dabd7771-f8f9-4def-86d3-1e72ae2da2f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/div/fieldset[3]/table/tbody/tr/td[2]/div/div/span/span</value>
   </webElementProperties>
</WebElementEntity>
