<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown-Language</name>
   <tag></tag>
   <elementGuidId>de70e99b-4a17-4e15-aeaa-5e6c427c6bc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/div/fieldset[2]/table/tbody/tr[2]/td[2]/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
