<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dropdown-Gender</name>
   <tag></tag>
   <elementGuidId>2e0fb59d-53f7-4ebe-b162-d7fa658629da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='divBodyMain']/form/div/fieldset[1]/table/tbody/tr[4]/td[2]/div/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
